services:
  vocal-remover:
    build:
      context: .
      dockerfile: Dockerfile
    image: vocal-remover
    container_name: vocal-remover
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./app:/app/app  # Mount app directory for live code changes
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu] 